use std::path::PathBuf;

use axum::Router;
use axum::routing::{get, post};
use tower_http::services::ServeDir;
use tower_http::trace::TraceLayer;

use crate::middleware::security_headers;
use crate::routes;
use crate::state::AppState;

pub fn build(state: AppState) -> Router {
    Router::new()
        .route("/", get(routes::dashboard::show))
        .route(
            "/setup",
            get(routes::setup::show).post(routes::setup::submit),
        )
        .route(
            "/login",
            get(routes::login::show).post(routes::login::submit),
        )
        .route("/logout", post(routes::login::logout))
        .route(
            "/register",
            get(routes::register::show).post(routes::register::submit),
        )
        .route(
            "/forgot-password",
            get(routes::password_reset::show_forgot_password)
                .post(routes::password_reset::submit_forgot_password),
        )
        .route(
            "/reset-password",
            get(routes::password_reset::show_reset_password)
                .post(routes::password_reset::submit_reset_password),
        )
        .route("/theme", post(routes::theme::set))
        .route("/account", get(routes::account::show))
        .route("/account/timezone", post(routes::account::set_timezone))
        .route("/account/password", post(routes::account::change_password))
        .route("/modules/:key/pin", post(routes::dashboard::pin))
        .route("/modules/:key/unpin", post(routes::dashboard::unpin))
        .route("/host-context/select", post(routes::host_context::select))
        .route("/style-guide", get(routes::style_guide::show))
        .route("/admin/users", get(routes::users::list))
        .route("/admin/users/create", post(routes::users::create))
        .route("/admin/users/:id/enable", post(routes::users::enable))
        .route(
            "/admin/users/:id/disable/confirm",
            get(routes::users::disable_confirm),
        )
        .route("/admin/users/:id/disable", post(routes::users::disable))
        .route(
            "/admin/users/:id/revoke-sessions/confirm",
            get(routes::users::revoke_sessions_confirm),
        )
        .route(
            "/admin/users/:id/revoke-sessions",
            post(routes::users::revoke_sessions),
        )
        .route(
            "/admin/users/:id/delete/confirm",
            get(routes::users::delete_confirm),
        )
        .route("/admin/users/:id/delete", post(routes::users::delete))
        .route("/admin/roles", get(routes::roles::list))
        .route(
            "/admin/roles/:id/permissions",
            post(routes::roles::update_permissions),
        )
        .route(
            "/admin/roles/:id/permissions/apply",
            post(routes::roles::apply_permissions),
        )
        .route(
            "/admin/roles/:id/visibility",
            post(routes::roles::update_visibility),
        )
        .route("/admin/audit", get(routes::audit::list))
        .route("/admin/audit/export", get(routes::audit::export))
        .route("/admin/modules", get(routes::modules::list))
        .route("/admin/modules/:key/enable", post(routes::modules::enable))
        .route(
            "/admin/modules/:key/disable/confirm",
            get(routes::modules::disable_confirm),
        )
        .route(
            "/admin/modules/:key/disable",
            post(routes::modules::disable),
        )
        .route("/admin/workflows", get(routes::workflows::list))
        .route("/admin/settings", get(routes::settings::show))
        .route(
            "/admin/settings/registration",
            post(routes::settings::set_registration),
        )
        .route(
            "/admin/settings/elevation-window",
            post(routes::settings::set_elevation_window),
        )
        .route(
            "/admin/settings/high-risk-storage-ops",
            post(routes::settings::set_high_risk_storage_ops),
        )
        .route(
            "/admin/settings/host-isolation",
            post(routes::settings::set_host_isolation),
        )
        .route(
            "/admin/settings/thanatos-monitoring",
            post(routes::settings::set_thanatos_monitoring),
        )
        .route(
            "/admin/settings/thanatos-alert-recipients",
            post(routes::settings::set_thanatos_alert_recipients),
        )
        .route(
            "/admin/settings/panopticon-sweep-enabled",
            post(routes::settings::set_panopticon_sweep_enabled),
        )
        .route(
            "/admin/settings/panopticon-sweep-target",
            post(routes::settings::set_panopticon_sweep_target),
        )
        .route(
            "/admin/settings/panopticon-mdns-enabled",
            post(routes::settings::set_panopticon_mdns_enabled),
        )
        .route(
            "/admin/settings/panopticon-arp-enabled",
            post(routes::settings::set_panopticon_arp_enabled),
        )
        .route(
            "/admin/settings/panopticon-arp-interface",
            post(routes::settings::set_panopticon_arp_interface),
        )
        .route("/admin/hosts", get(routes::hosts::list))
        .route(
            "/admin/hosts/enroll-token",
            post(routes::hosts::generate_enrollment_token),
        )
        .route(
            "/admin/hosts/:id/system-info",
            post(routes::hosts::run_system_info),
        )
        .route(
            "/admin/hosts/:id/deescalate",
            post(routes::hosts::deescalate),
        )
        .route(
            "/admin/hosts/:id/revoke/confirm",
            get(routes::hosts::revoke_confirm),
        )
        .route("/admin/hosts/:id/revoke", post(routes::hosts::revoke))
        .route(
            "/admin/hosts/:id/remove/confirm",
            get(routes::hosts::remove_confirm),
        )
        .route("/admin/hosts/:id/remove", post(routes::hosts::remove))
        .route("/arsenals/cystoolbox", get(routes::cystoolbox::show))
        .route(
            "/arsenals/cystoolbox/:host_id",
            get(routes::cystoolbox::show_host),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/system-overview",
            post(routes::cystoolbox::system_overview),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/resource-usage",
            post(routes::cystoolbox::resource_usage),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/logged-in-users",
            post(routes::cystoolbox::logged_in_users),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/set-hostname",
            post(routes::cystoolbox::set_hostname),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/reboot/confirm",
            get(routes::cystoolbox::reboot_confirm),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/reboot",
            post(routes::cystoolbox::reboot),
        )
        .route(
            "/arsenals/cystoolbox/:host_id/elevate",
            post(routes::cystoolbox::elevate),
        )
        .route("/arsenals/cadavault", get(routes::cadavault::show))
        .route(
            "/arsenals/cadavault/:host_id",
            get(routes::cadavault::show_host),
        )
        .route(
            "/arsenals/cadavault/:host_id/firewall-status",
            post(routes::cadavault::firewall_status),
        )
        .route(
            "/arsenals/cadavault/:host_id/listening-ports",
            post(routes::cadavault::listening_ports),
        )
        .route(
            "/arsenals/cadavault/:host_id/recent-auth-log",
            post(routes::cadavault::recent_auth_log),
        )
        .route(
            "/arsenals/cadavault/:host_id/allow-port",
            post(routes::cadavault::allow_port),
        )
        .route(
            "/arsenals/cadavault/:host_id/firewall-enable/confirm",
            get(routes::cadavault::enable_firewall_confirm),
        )
        .route(
            "/arsenals/cadavault/:host_id/firewall-enable",
            post(routes::cadavault::enable_firewall),
        )
        .route(
            "/arsenals/cadavault/:host_id/elevate",
            post(routes::cadavault::elevate),
        )
        .route("/arsenals/necrolink", get(routes::necrolink::show))
        .route(
            "/arsenals/necrolink/:host_id",
            get(routes::necrolink::show_host),
        )
        .route(
            "/arsenals/necrolink/:host_id/interfaces",
            post(routes::necrolink::network_interfaces),
        )
        .route(
            "/arsenals/necrolink/:host_id/routes",
            post(routes::necrolink::network_routes),
        )
        .route(
            "/arsenals/necrolink/:host_id/dns",
            post(routes::necrolink::dns_config),
        )
        .route(
            "/arsenals/necrolink/:host_id/connections",
            post(routes::necrolink::active_connections),
        )
        .route(
            "/arsenals/necrolink/:host_id/connectivity-check",
            post(routes::necrolink::connectivity_check),
        )
        .route(
            "/arsenals/necrolink/:host_id/interface/up",
            post(routes::necrolink::interface_up),
        )
        .route(
            "/arsenals/necrolink/:host_id/interface/down/confirm",
            get(routes::necrolink::interface_down_confirm),
        )
        .route(
            "/arsenals/necrolink/:host_id/interface/down",
            post(routes::necrolink::interface_down),
        )
        .route(
            "/arsenals/necrolink/:host_id/scan/confirm",
            get(routes::necrolink::scan_confirm),
        )
        .route(
            "/arsenals/necrolink/:host_id/scan",
            post(routes::necrolink::network_scan),
        )
        .route(
            "/arsenals/necrolink/:host_id/elevate",
            post(routes::necrolink::elevate),
        )
        .route("/arsenals/postmortem", get(routes::postmortem::show))
        .route(
            "/arsenals/postmortem/:host_id",
            get(routes::postmortem::show_host),
        )
        .route(
            "/arsenals/postmortem/:host_id/boot-history",
            post(routes::postmortem::boot_history),
        )
        .route(
            "/arsenals/postmortem/:host_id/kernel-ring-buffer",
            post(routes::postmortem::kernel_ring_buffer),
        )
        .route(
            "/arsenals/postmortem/:host_id/journal-errors",
            post(routes::postmortem::system_journal_errors),
        )
        .route(
            "/arsenals/postmortem/:host_id/failed-logins",
            post(routes::postmortem::failed_login_attempts),
        )
        .route(
            "/arsenals/postmortem/:host_id/oom-kills",
            post(routes::postmortem::oom_kill_events),
        )
        .route(
            "/arsenals/postmortem/:host_id/core-dumps",
            post(routes::postmortem::core_dumps),
        )
        .route(
            "/arsenals/postmortem/:host_id/modified-files",
            post(routes::postmortem::recently_modified_files),
        )
        .route(
            "/arsenals/postmortem/:host_id/elevate",
            post(routes::postmortem::elevate),
        )
        .route("/arsenals/obituary", get(routes::obituary::show))
        .route(
            "/arsenals/obituary/:host_id",
            get(routes::obituary::show_host),
        )
        .route(
            "/arsenals/obituary/:host_id/journal-disk-usage",
            post(routes::obituary::journal_disk_usage),
        )
        .route(
            "/arsenals/obituary/:host_id/log-rotation-status",
            post(routes::obituary::log_rotation_status),
        )
        .route(
            "/arsenals/obituary/:host_id/archived-logs",
            post(routes::obituary::archived_log_listing),
        )
        .route(
            "/arsenals/obituary/:host_id/log-directory-sizes",
            post(routes::obituary::log_directory_sizes),
        )
        .route(
            "/arsenals/obituary/:host_id/vacuum-size/confirm",
            get(routes::obituary::vacuum_size_confirm),
        )
        .route(
            "/arsenals/obituary/:host_id/vacuum-size",
            post(routes::obituary::vacuum_by_size),
        )
        .route(
            "/arsenals/obituary/:host_id/vacuum-time/confirm",
            get(routes::obituary::vacuum_time_confirm),
        )
        .route(
            "/arsenals/obituary/:host_id/vacuum-time",
            post(routes::obituary::vacuum_by_time),
        )
        .route(
            "/arsenals/obituary/:host_id/elevate",
            post(routes::obituary::elevate),
        )
        .route("/arsenals/reliquary", get(routes::reliquary::show))
        .route(
            "/arsenals/reliquary/:host_id",
            get(routes::reliquary::show_host),
        )
        .route(
            "/arsenals/reliquary/:host_id/list",
            post(routes::reliquary::list_backups),
        )
        .route(
            "/arsenals/reliquary/:host_id/verify",
            post(routes::reliquary::verify_backup),
        )
        .route(
            "/arsenals/reliquary/:host_id/create",
            post(routes::reliquary::create_backup),
        )
        .route(
            "/arsenals/reliquary/:host_id/restore/confirm",
            get(routes::reliquary::restore_confirm),
        )
        .route(
            "/arsenals/reliquary/:host_id/restore",
            post(routes::reliquary::restore_backup),
        )
        .route(
            "/arsenals/reliquary/:host_id/elevate",
            post(routes::reliquary::elevate),
        )
        .route("/arsenals/mortiscope", get(routes::mortiscope::show))
        .route(
            "/arsenals/mortiscope/:host_id",
            get(routes::mortiscope::show_host),
        )
        .route(
            "/arsenals/mortiscope/:host_id/load-average",
            post(routes::mortiscope::load_average),
        )
        .route(
            "/arsenals/mortiscope/:host_id/top-cpu",
            post(routes::mortiscope::top_processes_by_cpu),
        )
        .route(
            "/arsenals/mortiscope/:host_id/top-memory",
            post(routes::mortiscope::top_processes_by_memory),
        )
        .route(
            "/arsenals/mortiscope/:host_id/memory-detail",
            post(routes::mortiscope::memory_detail),
        )
        .route(
            "/arsenals/mortiscope/:host_id/disk-io",
            post(routes::mortiscope::disk_io_stats),
        )
        .route(
            "/arsenals/mortiscope/:host_id/failed-services",
            post(routes::mortiscope::failed_services),
        )
        .route(
            "/arsenals/mortiscope/:host_id/elevate",
            post(routes::mortiscope::elevate),
        )
        .route("/arsenals/incarnation", get(routes::incarnation::show))
        .route(
            "/arsenals/incarnation/:host_id",
            get(routes::incarnation::show_host),
        )
        .route(
            "/arsenals/incarnation/:host_id/list",
            post(routes::incarnation::list_services),
        )
        .route(
            "/arsenals/incarnation/:host_id/status",
            post(routes::incarnation::service_status),
        )
        .route(
            "/arsenals/incarnation/:host_id/logs",
            post(routes::incarnation::service_logs),
        )
        .route(
            "/arsenals/incarnation/:host_id/start",
            post(routes::incarnation::start_service),
        )
        .route(
            "/arsenals/incarnation/:host_id/enable",
            post(routes::incarnation::enable_service),
        )
        .route(
            "/arsenals/incarnation/:host_id/disable",
            post(routes::incarnation::disable_service),
        )
        .route(
            "/arsenals/incarnation/:host_id/stop/confirm",
            get(routes::incarnation::stop_confirm),
        )
        .route(
            "/arsenals/incarnation/:host_id/stop",
            post(routes::incarnation::stop_service),
        )
        .route(
            "/arsenals/incarnation/:host_id/restart/confirm",
            get(routes::incarnation::restart_confirm),
        )
        .route(
            "/arsenals/incarnation/:host_id/restart",
            post(routes::incarnation::restart_service),
        )
        .route(
            "/arsenals/incarnation/:host_id/elevate",
            post(routes::incarnation::elevate),
        )
        .route("/arsenals/resurrection", get(routes::resurrection::show))
        .route(
            "/arsenals/resurrection/:host_id",
            get(routes::resurrection::show_host),
        )
        .route(
            "/arsenals/resurrection/:host_id/previous-boot-errors",
            post(routes::resurrection::previous_boot_errors),
        )
        .route(
            "/arsenals/resurrection/:host_id/system-state",
            post(routes::resurrection::system_running_state),
        )
        .route(
            "/arsenals/resurrection/:host_id/ro-filesystems",
            post(routes::resurrection::read_only_filesystems),
        )
        .route(
            "/arsenals/resurrection/:host_id/daemon-reload",
            post(routes::resurrection::reload_systemd_daemon),
        )
        .route(
            "/arsenals/resurrection/:host_id/reset-failed",
            post(routes::resurrection::reset_failed_units),
        )
        .route(
            "/arsenals/resurrection/:host_id/remount/confirm",
            get(routes::resurrection::remount_confirm),
        )
        .route(
            "/arsenals/resurrection/:host_id/remount",
            post(routes::resurrection::remount_read_write),
        )
        .route(
            "/arsenals/resurrection/:host_id/elevate",
            post(routes::resurrection::elevate),
        )
        .route("/arsenals/necropsy", get(routes::necropsy::show))
        .route(
            "/arsenals/necropsy/:host_id",
            get(routes::necropsy::show_host),
        )
        .route(
            "/arsenals/necropsy/:host_id/cpu",
            post(routes::necropsy::cpu_info),
        )
        .route(
            "/arsenals/necropsy/:host_id/pci",
            post(routes::necropsy::pci_devices),
        )
        .route(
            "/arsenals/necropsy/:host_id/block-devices",
            post(routes::necropsy::block_devices),
        )
        .route(
            "/arsenals/necropsy/:host_id/memory-hardware",
            post(routes::necropsy::memory_hardware),
        )
        .route(
            "/arsenals/necropsy/:host_id/disk-health",
            post(routes::necropsy::disk_health),
        )
        .route(
            "/arsenals/necropsy/:host_id/elevate",
            post(routes::necropsy::elevate),
        )
        .route("/arsenals/necropolis", get(routes::necropolis::show))
        .route(
            "/arsenals/necropolis/:host_id",
            get(routes::necropolis::show_host),
        )
        .route(
            "/arsenals/necropolis/:host_id/list",
            post(routes::necropolis::list_containers),
        )
        .route(
            "/arsenals/necropolis/:host_id/images",
            post(routes::necropolis::list_images),
        )
        .route(
            "/arsenals/necropolis/:host_id/info",
            post(routes::necropolis::runtime_info),
        )
        .route(
            "/arsenals/necropolis/:host_id/logs",
            post(routes::necropolis::container_logs),
        )
        .route(
            "/arsenals/necropolis/:host_id/inspect",
            post(routes::necropolis::container_inspect),
        )
        .route(
            "/arsenals/necropolis/:host_id/start",
            post(routes::necropolis::start_container),
        )
        .route(
            "/arsenals/necropolis/:host_id/stop/confirm",
            get(routes::necropolis::stop_confirm),
        )
        .route(
            "/arsenals/necropolis/:host_id/stop",
            post(routes::necropolis::stop_container),
        )
        .route(
            "/arsenals/necropolis/:host_id/restart/confirm",
            get(routes::necropolis::restart_confirm),
        )
        .route(
            "/arsenals/necropolis/:host_id/restart",
            post(routes::necropolis::restart_container),
        )
        .route(
            "/arsenals/necropolis/:host_id/remove/confirm",
            get(routes::necropolis::remove_confirm),
        )
        .route(
            "/arsenals/necropolis/:host_id/remove",
            post(routes::necropolis::remove_container),
        )
        .route(
            "/arsenals/necropolis/:host_id/elevate",
            post(routes::necropolis::elevate),
        )
        .route("/arsenals/reanimation", get(routes::reanimation::show))
        .route(
            "/arsenals/reanimation/:host_id",
            get(routes::reanimation::show_host),
        )
        .route(
            "/arsenals/reanimation/:host_id/list",
            post(routes::reanimation::list_processes),
        )
        .route(
            "/arsenals/reanimation/:host_id/detail",
            post(routes::reanimation::process_detail),
        )
        .route(
            "/arsenals/reanimation/:host_id/renice",
            post(routes::reanimation::renice_priority),
        )
        .route(
            "/arsenals/reanimation/:host_id/signal/confirm",
            get(routes::reanimation::signal_confirm),
        )
        .route(
            "/arsenals/reanimation/:host_id/signal",
            post(routes::reanimation::send_signal),
        )
        .route(
            "/arsenals/reanimation/:host_id/elevate",
            post(routes::reanimation::elevate),
        )
        .route("/arsenals/defleshing", get(routes::defleshing::show))
        .route(
            "/arsenals/defleshing/:host_id",
            get(routes::defleshing::show_host),
        )
        .route(
            "/arsenals/defleshing/:host_id/summary",
            post(routes::defleshing::cleanup_targets_summary),
        )
        .route(
            "/arsenals/defleshing/:host_id/rotate-logs",
            post(routes::defleshing::force_log_rotation),
        )
        .route(
            "/arsenals/defleshing/:host_id/clear-tmp/confirm",
            get(routes::defleshing::clear_tmp_confirm),
        )
        .route(
            "/arsenals/defleshing/:host_id/clear-tmp",
            post(routes::defleshing::clear_tmp_files),
        )
        .route(
            "/arsenals/defleshing/:host_id/clear-core-dumps/confirm",
            get(routes::defleshing::clear_core_dumps_confirm),
        )
        .route(
            "/arsenals/defleshing/:host_id/clear-core-dumps",
            post(routes::defleshing::clear_core_dumps),
        )
        .route(
            "/arsenals/defleshing/:host_id/elevate",
            post(routes::defleshing::elevate),
        )
        .route("/arsenals/vivisection", get(routes::vivisection::show))
        .route(
            "/arsenals/vivisection/:host_id",
            get(routes::vivisection::show_host),
        )
        .route(
            "/arsenals/vivisection/:host_id/vmstat",
            post(routes::vivisection::vm_statistics),
        )
        .route(
            "/arsenals/vivisection/:host_id/interrupts",
            post(routes::vivisection::interrupt_statistics),
        )
        .route(
            "/arsenals/vivisection/:host_id/cpu-governor",
            post(routes::vivisection::cpu_governor_status),
        )
        .route(
            "/arsenals/vivisection/:host_id/tuning-params",
            post(routes::vivisection::tuning_parameters_status),
        )
        .route(
            "/arsenals/vivisection/:host_id/swappiness",
            post(routes::vivisection::set_swappiness),
        )
        .route(
            "/arsenals/vivisection/:host_id/io-scheduler",
            post(routes::vivisection::set_io_scheduler),
        )
        .route(
            "/arsenals/vivisection/:host_id/elevate",
            post(routes::vivisection::elevate),
        )
        .route("/arsenals/parish", get(routes::parish::show))
        .route("/arsenals/parish/:host_id", get(routes::parish::show_host))
        .route(
            "/arsenals/parish/:host_id/users",
            post(routes::parish::list_users),
        )
        .route(
            "/arsenals/parish/:host_id/groups",
            post(routes::parish::list_groups),
        )
        .route(
            "/arsenals/parish/:host_id/user-detail",
            post(routes::parish::user_detail),
        )
        .route(
            "/arsenals/parish/:host_id/create-user",
            post(routes::parish::create_user),
        )
        .route(
            "/arsenals/parish/:host_id/create-group",
            post(routes::parish::create_group),
        )
        .route(
            "/arsenals/parish/:host_id/add-to-group",
            post(routes::parish::add_user_to_group),
        )
        .route(
            "/arsenals/parish/:host_id/remove-from-group",
            post(routes::parish::remove_user_from_group),
        )
        .route(
            "/arsenals/parish/:host_id/lock",
            post(routes::parish::lock_user_account),
        )
        .route(
            "/arsenals/parish/:host_id/unlock",
            post(routes::parish::unlock_user_account),
        )
        .route(
            "/arsenals/parish/:host_id/delete-user/confirm",
            get(routes::parish::delete_user_confirm),
        )
        .route(
            "/arsenals/parish/:host_id/delete-user",
            post(routes::parish::delete_user),
        )
        .route(
            "/arsenals/parish/:host_id/delete-group/confirm",
            get(routes::parish::delete_group_confirm),
        )
        .route(
            "/arsenals/parish/:host_id/delete-group",
            post(routes::parish::delete_group),
        )
        .route(
            "/arsenals/parish/:host_id/elevate",
            post(routes::parish::elevate),
        )
        .route("/arsenals/catacomb", get(routes::catacomb::show))
        .route(
            "/arsenals/catacomb/:host_id",
            get(routes::catacomb::show_host),
        )
        .route(
            "/arsenals/catacomb/:host_id/du",
            post(routes::catacomb::directory_usage_breakdown),
        )
        .route(
            "/arsenals/catacomb/:host_id/large-files",
            post(routes::catacomb::find_large_files),
        )
        .route(
            "/arsenals/catacomb/:host_id/fsck-check",
            post(routes::catacomb::filesystem_check_dry_run),
        )
        .route(
            "/arsenals/catacomb/:host_id/trim",
            post(routes::catacomb::trim_filesystem),
        )
        .route(
            "/arsenals/catacomb/:host_id/repair/confirm",
            get(routes::catacomb::filesystem_repair_confirm),
        )
        .route(
            "/arsenals/catacomb/:host_id/repair",
            post(routes::catacomb::filesystem_repair),
        )
        .route(
            "/arsenals/catacomb/:host_id/elevate",
            post(routes::catacomb::elevate),
        )
        .route("/arsenals/apothecary", get(routes::apothecary::show))
        .route(
            "/arsenals/apothecary/:host_id",
            get(routes::apothecary::show_host),
        )
        .route(
            "/arsenals/apothecary/:host_id/list",
            post(routes::apothecary::list_installed_packages),
        )
        .route(
            "/arsenals/apothecary/:host_id/upgradable",
            post(routes::apothecary::list_upgradable),
        )
        .route(
            "/arsenals/apothecary/:host_id/search",
            post(routes::apothecary::search_package),
        )
        .route(
            "/arsenals/apothecary/:host_id/info",
            post(routes::apothecary::package_info),
        )
        .route(
            "/arsenals/apothecary/:host_id/refresh",
            post(routes::apothecary::refresh_package_index),
        )
        .route(
            "/arsenals/apothecary/:host_id/install",
            post(routes::apothecary::install_package),
        )
        .route(
            "/arsenals/apothecary/:host_id/upgrade",
            post(routes::apothecary::upgrade_package),
        )
        .route(
            "/arsenals/apothecary/:host_id/remove/confirm",
            get(routes::apothecary::remove_package_confirm),
        )
        .route(
            "/arsenals/apothecary/:host_id/remove",
            post(routes::apothecary::remove_package),
        )
        .route(
            "/arsenals/apothecary/:host_id/elevate",
            post(routes::apothecary::elevate),
        )
        .route("/arsenals/ossuary", get(routes::ossuary::show))
        .route(
            "/arsenals/ossuary/:host_id",
            get(routes::ossuary::show_host),
        )
        .route(
            "/arsenals/ossuary/:host_id/partition-table",
            post(routes::ossuary::partition_table),
        )
        .route(
            "/arsenals/ossuary/:host_id/lvm-summary",
            post(routes::ossuary::lvm_summary),
        )
        .route(
            "/arsenals/ossuary/:host_id/raid-status",
            post(routes::ossuary::raid_status),
        )
        .route(
            "/arsenals/ossuary/:host_id/mount",
            post(routes::ossuary::mount_filesystem),
        )
        .route(
            "/arsenals/ossuary/:host_id/extend-lv",
            post(routes::ossuary::extend_logical_volume),
        )
        .route(
            "/arsenals/ossuary/:host_id/unmount/confirm",
            get(routes::ossuary::unmount_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/unmount",
            post(routes::ossuary::unmount_filesystem),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-partition/confirm",
            get(routes::ossuary::create_partition_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-partition",
            post(routes::ossuary::create_partition),
        )
        .route(
            "/arsenals/ossuary/:host_id/delete-partition/confirm",
            get(routes::ossuary::delete_partition_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/delete-partition",
            post(routes::ossuary::delete_partition),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-raid/confirm",
            get(routes::ossuary::create_raid_array_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-raid",
            post(routes::ossuary::create_raid_array),
        )
        .route(
            "/arsenals/ossuary/:host_id/stop-raid/confirm",
            get(routes::ossuary::stop_raid_array_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/stop-raid",
            post(routes::ossuary::stop_raid_array),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-pv/confirm",
            get(routes::ossuary::create_physical_volume_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-pv",
            post(routes::ossuary::create_physical_volume),
        )
        .route(
            "/arsenals/ossuary/:host_id/remove-pv/confirm",
            get(routes::ossuary::remove_physical_volume_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/remove-pv",
            post(routes::ossuary::remove_physical_volume),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-vg/confirm",
            get(routes::ossuary::create_volume_group_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-vg",
            post(routes::ossuary::create_volume_group),
        )
        .route(
            "/arsenals/ossuary/:host_id/remove-vg/confirm",
            get(routes::ossuary::remove_volume_group_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/remove-vg",
            post(routes::ossuary::remove_volume_group),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-lv/confirm",
            get(routes::ossuary::create_logical_volume_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/create-lv",
            post(routes::ossuary::create_logical_volume),
        )
        .route(
            "/arsenals/ossuary/:host_id/remove-lv/confirm",
            get(routes::ossuary::remove_logical_volume_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/remove-lv",
            post(routes::ossuary::remove_logical_volume),
        )
        .route(
            "/arsenals/ossuary/:host_id/mkfs/confirm",
            get(routes::ossuary::create_filesystem_confirm),
        )
        .route(
            "/arsenals/ossuary/:host_id/mkfs",
            post(routes::ossuary::create_filesystem),
        )
        .route(
            "/arsenals/ossuary/:host_id/elevate",
            post(routes::ossuary::elevate),
        )
        .route("/arsenals/grimoire", get(routes::grimoire::show))
        .route(
            "/arsenals/grimoire/:host_id",
            get(routes::grimoire::show_host),
        )
        .route(
            "/arsenals/grimoire/:host_id/view-sysctl",
            post(routes::grimoire::view_managed_sysctl),
        )
        .route(
            "/arsenals/grimoire/:host_id/view-cron",
            post(routes::grimoire::view_managed_cron_jobs),
        )
        .route(
            "/arsenals/grimoire/:host_id/set-sysctl",
            post(routes::grimoire::set_persistent_sysctl),
        )
        .route(
            "/arsenals/grimoire/:host_id/remove-sysctl-key",
            post(routes::grimoire::remove_persistent_sysctl_key),
        )
        .route(
            "/arsenals/grimoire/:host_id/set-cron",
            post(routes::grimoire::set_cron_job),
        )
        .route(
            "/arsenals/grimoire/:host_id/remove-cron/confirm",
            get(routes::grimoire::remove_cron_job_confirm),
        )
        .route(
            "/arsenals/grimoire/:host_id/remove-cron",
            post(routes::grimoire::remove_cron_job),
        )
        .route(
            "/arsenals/grimoire/:host_id/clear-sysctl/confirm",
            get(routes::grimoire::clear_managed_sysctl_confirm),
        )
        .route(
            "/arsenals/grimoire/:host_id/clear-sysctl",
            post(routes::grimoire::clear_managed_sysctl),
        )
        .route(
            "/arsenals/grimoire/:host_id/clear-cron/confirm",
            get(routes::grimoire::clear_managed_cron_jobs_confirm),
        )
        .route(
            "/arsenals/grimoire/:host_id/clear-cron",
            post(routes::grimoire::clear_managed_cron_jobs),
        )
        .route(
            "/arsenals/grimoire/:host_id/elevate",
            post(routes::grimoire::elevate),
        )
        .route("/arsenals/inquest", get(routes::inquest::show))
        .route(
            "/arsenals/inquest/:host_id",
            get(routes::inquest::show_host),
        )
        .route(
            "/arsenals/inquest/:host_id/blocked-ips",
            post(routes::inquest::list_blocked_ips),
        )
        .route(
            "/arsenals/inquest/:host_id/isolation-status",
            post(routes::inquest::isolation_status),
        )
        .route(
            "/arsenals/inquest/:host_id/quarantined-files",
            post(routes::inquest::list_quarantined_files),
        )
        .route(
            "/arsenals/inquest/:host_id/block-ip",
            post(routes::inquest::block_remote_ip),
        )
        .route(
            "/arsenals/inquest/:host_id/unblock-ip",
            post(routes::inquest::unblock_remote_ip),
        )
        .route(
            "/arsenals/inquest/:host_id/quarantine",
            post(routes::inquest::quarantine_file),
        )
        .route(
            "/arsenals/inquest/:host_id/restore-quarantined",
            post(routes::inquest::restore_quarantined_file),
        )
        .route(
            "/arsenals/inquest/:host_id/deisolate",
            post(routes::inquest::deisolate_host),
        )
        .route(
            "/arsenals/inquest/:host_id/delete-quarantined/confirm",
            get(routes::inquest::delete_quarantined_file_confirm),
        )
        .route(
            "/arsenals/inquest/:host_id/delete-quarantined",
            post(routes::inquest::delete_quarantined_file),
        )
        .route(
            "/arsenals/inquest/:host_id/isolate/confirm",
            get(routes::inquest::isolate_host_confirm),
        )
        .route(
            "/arsenals/inquest/:host_id/isolate",
            post(routes::inquest::isolate_host),
        )
        .route(
            "/arsenals/inquest/:host_id/elevate",
            post(routes::inquest::elevate),
        )
        .route("/arsenals/cryptkeeper", get(routes::cryptkeeper::show))
        .route(
            "/arsenals/cryptkeeper/:host_id",
            get(routes::cryptkeeper::show_host),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/ssh-host-keys",
            post(routes::cryptkeeper::list_ssh_host_keys),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/authorized-keys",
            post(routes::cryptkeeper::list_ssh_authorized_keys),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/tls-certificates",
            post(routes::cryptkeeper::list_tls_certificates),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/certificate-detail",
            post(routes::cryptkeeper::certificate_detail),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/permission-scan",
            post(routes::cryptkeeper::scan_sensitive_file_permissions),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/view-file",
            post(routes::cryptkeeper::view_sensitive_file),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/generate-keypair",
            post(routes::cryptkeeper::generate_ssh_keypair),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/fix-permissions",
            post(routes::cryptkeeper::fix_file_permissions),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/remove-authorized-key/confirm",
            get(routes::cryptkeeper::remove_authorized_key_confirm),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/remove-authorized-key",
            post(routes::cryptkeeper::remove_authorized_key),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/delete-ssh-keypair/confirm",
            get(routes::cryptkeeper::delete_ssh_keypair_confirm),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/delete-ssh-keypair",
            post(routes::cryptkeeper::delete_ssh_keypair),
        )
        .route(
            "/arsenals/cryptkeeper/:host_id/elevate",
            post(routes::cryptkeeper::elevate),
        )
        .route("/arsenals/panopticon", get(routes::panopticon::show))
        .route(
            "/arsenals/panopticon/scan/confirm",
            get(routes::panopticon::scan_confirm),
        )
        .route("/arsenals/panopticon/scan", post(routes::panopticon::scan))
        .route(
            "/arsenals/panopticon/devices/:id/remove/confirm",
            get(routes::panopticon::remove_device_confirm),
        )
        .route(
            "/arsenals/panopticon/devices/:id/remove",
            post(routes::panopticon::remove_device),
        )
        .route(
            "/arsenals/panopticon/devices/:id/classify",
            get(routes::panopticon::classify_form).post(routes::panopticon::classify_device),
        )
        .route(
            "/arsenals/panopticon/switches",
            get(routes::panopticon::switches_show).post(routes::panopticon::switch_add),
        )
        .route(
            "/arsenals/panopticon/switches/:id/enabled",
            post(routes::panopticon::switch_set_enabled),
        )
        .route(
            "/arsenals/panopticon/switches/:id/poll",
            post(routes::panopticon::switch_poll_now),
        )
        .route(
            "/arsenals/panopticon/switches/:id/remove/confirm",
            get(routes::panopticon::switch_remove_confirm),
        )
        .route(
            "/arsenals/panopticon/switches/:id/remove",
            post(routes::panopticon::switch_remove),
        )
        .route("/arsenals/thanatos", get(routes::thanatos::show))
        .route(
            "/arsenals/thanatos/:host_id",
            get(routes::thanatos::show_host),
        )
        .route(
            "/arsenals/thanatos/:host_id/scan",
            post(routes::thanatos::scan),
        )
        .route(
            "/arsenals/thanatos/:host_id/elevate",
            post(routes::thanatos::elevate),
        )
        .route("/arsenals/:key", get(routes::arsenals::show))
        .route("/api/health", get(routes::api::health))
        .route("/api/me", get(routes::api::me))
        .route("/api/hosts/enroll", post(routes::agent::enroll))
        .route("/ws/agent", get(routes::agent::ws_upgrade))
        .nest_service("/static", ServeDir::new(static_dir()))
        .layer(axum::middleware::from_fn(security_headers::apply))
        .layer(TraceLayer::new_for_http())
        .with_state(state)
}

/// Defaults to the path that works with `cargo run` from the workspace root;
/// the Docker image sets `STATIC_DIR=static` after copying
/// `crates/web/static/` alongside the binary.
fn static_dir() -> PathBuf {
    std::env::var("STATIC_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("crates/web/static"))
}
