/// Every security-sensitive action the platform records. New actions should be
/// added here rather than as free-form strings scattered across handlers, so
/// the audit viewer's action filter always has a complete, typo-proof list.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditAction {
    UserCreated,
    UserEnabled,
    UserDisabled,
    UserDeleted,
    SessionsRevoked,
    RoleChanged,
    LoginSuccess,
    LoginFailure,
    Logout,
    PasswordChanged,
    PasswordResetRequested,
    PasswordReset,
    SsoLogin,
    ModuleEnabled,
    ModuleDisabled,
    SystemCommandExecuted,
    ConfigurationChanged,
    AuditExported,
    SecretAccessed,
    BackupCreated,
    BackupRestored,
    BackupVerified,
    BackupDeleted,
    BackupDownloaded,
    BackupSettingsChanged,
    HostEnrolled,
    HostApproved,
    /// A host was flagged (or unflagged) as the control plane's own server.
    HostControlPlaneChanged,
    SanitizationSignedOff,
    HostRevoked,
    HostRemoved,
    HostElevated,
    HostElevationFailed,
    HostDeescalated,
    HostElevationExpired,
    NetworkDeviceRemoved,
    NetworkSubnetRemoved,
    NetworkSubnetsRederived,
    NetworkDeviceClassified,
    NetworkDeviceDiscovered,
    NetworkUntrustedDeviceSeen,
    NetworkSwitchAdded,
    NetworkSwitchUpdated,
    NetworkSwitchRemoved,
    /// DHCP leases imported into Panopticon (a pasted file or a managed
    /// DHCP server).
    NetworkDhcpLeasesImported,
    /// Panopticon NAC enforcement (phase 3): an SNMP SET actually written to
    /// a live switch to disable a port or move it to a quarantine VLAN.
    /// `metadata` always carries `{"kind": "disable" | "quarantine",
    /// "switch": ..., "port": ..., ...}`. `Failure` outcome means the SET was
    /// attempted but the switch rejected it or was unreachable.
    NetworkPortEnforced,
    /// The inverse: an enforced port restored to service (re-enabled, or its
    /// VLAN put back), whether by an operator clicking "Release" or by the
    /// auto-revert sweep when a timed action expired (`metadata.by`:
    /// `"operator"` | `"auto_revert"`).
    NetworkPortReleased,
    UserProfileUpdated,
    HostDeployStarted,
    HostDeploySucceeded,
    HostDeployFailed,
    WorkflowEvaluationFailed,
    MacroCreated,
    MacroUpdated,
    MacroDeleted,
    RoleCreated,
    RoleDeleted,
    UserRoleAssigned,
    SecurityEventScanRun,
    SecurityAlertRaised,
    SecurityEventAcknowledged,
    SecurityEventResolved,
    SecurityEventSuppressed,
    /// A Thanatos playbook automation (Phase 11) dispatched a response
    /// action on its own, with no human clicking anything -- distinct
    /// from Phase 7c's manual kill/disable-account routes, which
    /// deliberately reuse the generic executor audit trail instead of a
    /// custom action, since a human is always the one who clicked there.
    /// `metadata` always carries `{"action": "quarantine_file" |
    /// "disable_account", "host_id": ..., ...}` so the audit viewer can
    /// tell which automation fired and against what.
    AutomatedResponseTriggered,

    /// Sepulchre: storage connection definitions, shares, mounts, and
    /// their credentials. Secret-touching variants never carry the
    /// secret/key material itself in `metadata` -- only who/what/when/
    /// which connection, per GitHub issue #9's own established
    /// convention for backup encryption metadata.
    StorageConnectionCreated,
    StorageConnectionChanged,
    StorageConnectionDeleted,
    StorageConnectionValidated,
    StorageSecretReplaced,
    StorageKeypairGenerated,
    StorageKeypairImported,
    StorageShareProvisioned,
    StorageShareRemoved,
    StorageMountProvisioned,
    StorageMountRemoved,

    /// Scourge (network IDS/IPS). Config/rule/mode changes carry before/after
    /// context in `metadata` (never raw payloads). `ScourgeEventScanRun` is the
    /// unattended collection sweep's own record (it bypasses the executor's
    /// automatic auditing, like Thanatos's `SecurityEventScanRun`).
    ScourgeSensorConfigured,
    ScourgeRuleChanged,
    ScourgeModeChanged,
    ScourgeCaptureStarted,
    ScourgePcapDeleted,
    ScourgeSensorRemoved,
    ScourgeEventScanRun,
}

impl AuditAction {
    pub const fn as_key(self) -> &'static str {
        match self {
            AuditAction::UserCreated => "USER_CREATED",
            AuditAction::UserEnabled => "USER_ENABLED",
            AuditAction::UserDisabled => "USER_DISABLED",
            AuditAction::UserDeleted => "USER_DELETED",
            AuditAction::SessionsRevoked => "SESSIONS_REVOKED",
            AuditAction::RoleChanged => "ROLE_CHANGED",
            AuditAction::LoginSuccess => "LOGIN_SUCCESS",
            AuditAction::LoginFailure => "LOGIN_FAILURE",
            AuditAction::Logout => "LOGOUT",
            AuditAction::PasswordChanged => "PASSWORD_CHANGED",
            AuditAction::PasswordResetRequested => "PASSWORD_RESET_REQUESTED",
            AuditAction::PasswordReset => "PASSWORD_RESET",
            AuditAction::SsoLogin => "SSO_LOGIN",
            AuditAction::ModuleEnabled => "MODULE_ENABLED",
            AuditAction::ModuleDisabled => "MODULE_DISABLED",
            AuditAction::SystemCommandExecuted => "SYSTEM_COMMAND_EXECUTED",
            AuditAction::ConfigurationChanged => "CONFIGURATION_CHANGED",
            AuditAction::AuditExported => "AUDIT_EXPORTED",
            AuditAction::SecretAccessed => "SECRET_ACCESSED",
            AuditAction::BackupCreated => "BACKUP_CREATED",
            AuditAction::BackupRestored => "BACKUP_RESTORED",
            AuditAction::BackupVerified => "BACKUP_VERIFIED",
            AuditAction::BackupDeleted => "BACKUP_DELETED",
            AuditAction::BackupDownloaded => "BACKUP_DOWNLOADED",
            AuditAction::BackupSettingsChanged => "BACKUP_SETTINGS_CHANGED",
            AuditAction::HostEnrolled => "HOST_ENROLLED",
            AuditAction::HostApproved => "HOST_APPROVED",
            AuditAction::HostControlPlaneChanged => "HOST_CONTROL_PLANE_CHANGED",
            AuditAction::SanitizationSignedOff => "SANITIZATION_SIGNED_OFF",
            AuditAction::HostRevoked => "HOST_REVOKED",
            AuditAction::HostRemoved => "HOST_REMOVED",
            AuditAction::HostElevated => "HOST_ELEVATED",
            AuditAction::HostElevationFailed => "HOST_ELEVATION_FAILED",
            AuditAction::HostDeescalated => "HOST_DEESCALATED",
            AuditAction::HostElevationExpired => "HOST_ELEVATION_EXPIRED",
            AuditAction::NetworkDeviceRemoved => "NETWORK_DEVICE_REMOVED",
            AuditAction::NetworkDhcpLeasesImported => "NETWORK_DHCP_LEASES_IMPORTED",
            AuditAction::NetworkSubnetRemoved => "NETWORK_SUBNET_REMOVED",
            AuditAction::NetworkSubnetsRederived => "NETWORK_SUBNETS_REDERIVED",
            AuditAction::NetworkDeviceClassified => "NETWORK_DEVICE_CLASSIFIED",
            AuditAction::NetworkDeviceDiscovered => "NETWORK_DEVICE_DISCOVERED",
            AuditAction::NetworkUntrustedDeviceSeen => "NETWORK_UNTRUSTED_DEVICE_SEEN",
            AuditAction::NetworkSwitchAdded => "NETWORK_SWITCH_ADDED",
            AuditAction::NetworkSwitchUpdated => "NETWORK_SWITCH_UPDATED",
            AuditAction::NetworkSwitchRemoved => "NETWORK_SWITCH_REMOVED",
            AuditAction::NetworkPortEnforced => "NETWORK_PORT_ENFORCED",
            AuditAction::NetworkPortReleased => "NETWORK_PORT_RELEASED",
            AuditAction::UserProfileUpdated => "USER_PROFILE_UPDATED",
            AuditAction::HostDeployStarted => "HOST_DEPLOY_STARTED",
            AuditAction::HostDeploySucceeded => "HOST_DEPLOY_SUCCEEDED",
            AuditAction::HostDeployFailed => "HOST_DEPLOY_FAILED",
            AuditAction::WorkflowEvaluationFailed => "WORKFLOW_EVALUATION_FAILED",
            AuditAction::MacroCreated => "MACRO_CREATED",
            AuditAction::MacroUpdated => "MACRO_UPDATED",
            AuditAction::MacroDeleted => "MACRO_DELETED",
            AuditAction::RoleCreated => "ROLE_CREATED",
            AuditAction::RoleDeleted => "ROLE_DELETED",
            AuditAction::UserRoleAssigned => "USER_ROLE_ASSIGNED",
            AuditAction::SecurityEventScanRun => "SECURITY_EVENT_SCAN_RUN",
            AuditAction::SecurityAlertRaised => "SECURITY_ALERT_RAISED",
            AuditAction::SecurityEventAcknowledged => "SECURITY_EVENT_ACKNOWLEDGED",
            AuditAction::SecurityEventResolved => "SECURITY_EVENT_RESOLVED",
            AuditAction::SecurityEventSuppressed => "SECURITY_EVENT_SUPPRESSED",
            AuditAction::AutomatedResponseTriggered => "AUTOMATED_RESPONSE_TRIGGERED",

            AuditAction::StorageConnectionCreated => "STORAGE_CONNECTION_CREATED",
            AuditAction::StorageConnectionChanged => "STORAGE_CONNECTION_CHANGED",
            AuditAction::StorageConnectionDeleted => "STORAGE_CONNECTION_DELETED",
            AuditAction::StorageConnectionValidated => "STORAGE_CONNECTION_VALIDATED",
            AuditAction::StorageSecretReplaced => "STORAGE_SECRET_REPLACED",
            AuditAction::StorageKeypairGenerated => "STORAGE_KEYPAIR_GENERATED",
            AuditAction::StorageKeypairImported => "STORAGE_KEYPAIR_IMPORTED",
            AuditAction::StorageShareProvisioned => "STORAGE_SHARE_PROVISIONED",
            AuditAction::StorageShareRemoved => "STORAGE_SHARE_REMOVED",
            AuditAction::StorageMountProvisioned => "STORAGE_MOUNT_PROVISIONED",
            AuditAction::StorageMountRemoved => "STORAGE_MOUNT_REMOVED",
            AuditAction::ScourgeSensorConfigured => "SCOURGE_SENSOR_CONFIGURED",
            AuditAction::ScourgeRuleChanged => "SCOURGE_RULE_CHANGED",
            AuditAction::ScourgeModeChanged => "SCOURGE_MODE_CHANGED",
            AuditAction::ScourgeCaptureStarted => "SCOURGE_CAPTURE_STARTED",
            AuditAction::ScourgePcapDeleted => "SCOURGE_PCAP_DELETED",
            AuditAction::ScourgeSensorRemoved => "SCOURGE_SENSOR_REMOVED",
            AuditAction::ScourgeEventScanRun => "SCOURGE_EVENT_SCAN_RUN",
        }
    }

    pub const ALL: &'static [AuditAction] = &[
        AuditAction::UserCreated,
        AuditAction::UserEnabled,
        AuditAction::UserDisabled,
        AuditAction::UserDeleted,
        AuditAction::SessionsRevoked,
        AuditAction::RoleChanged,
        AuditAction::LoginSuccess,
        AuditAction::LoginFailure,
        AuditAction::Logout,
        AuditAction::PasswordChanged,
        AuditAction::PasswordResetRequested,
        AuditAction::PasswordReset,
        AuditAction::SsoLogin,
        AuditAction::ModuleEnabled,
        AuditAction::ModuleDisabled,
        AuditAction::SystemCommandExecuted,
        AuditAction::ConfigurationChanged,
        AuditAction::AuditExported,
        AuditAction::SecretAccessed,
        AuditAction::BackupCreated,
        AuditAction::BackupRestored,
        AuditAction::BackupVerified,
        AuditAction::BackupDeleted,
        AuditAction::BackupDownloaded,
        AuditAction::BackupSettingsChanged,
        AuditAction::HostEnrolled,
        AuditAction::HostApproved,
        AuditAction::HostControlPlaneChanged,
        AuditAction::SanitizationSignedOff,
        AuditAction::HostRevoked,
        AuditAction::HostRemoved,
        AuditAction::HostElevated,
        AuditAction::HostElevationFailed,
        AuditAction::HostDeescalated,
        AuditAction::HostElevationExpired,
        AuditAction::NetworkDeviceRemoved,
        AuditAction::NetworkSubnetRemoved,
        AuditAction::NetworkSubnetsRederived,
        AuditAction::NetworkDeviceClassified,
        AuditAction::NetworkDeviceDiscovered,
        AuditAction::NetworkUntrustedDeviceSeen,
        AuditAction::NetworkSwitchAdded,
        AuditAction::NetworkSwitchUpdated,
        AuditAction::NetworkSwitchRemoved,
        AuditAction::NetworkDhcpLeasesImported,
        AuditAction::NetworkPortEnforced,
        AuditAction::NetworkPortReleased,
        AuditAction::UserProfileUpdated,
        AuditAction::HostDeployStarted,
        AuditAction::HostDeploySucceeded,
        AuditAction::HostDeployFailed,
        AuditAction::WorkflowEvaluationFailed,
        AuditAction::MacroCreated,
        AuditAction::MacroUpdated,
        AuditAction::MacroDeleted,
        AuditAction::RoleCreated,
        AuditAction::RoleDeleted,
        AuditAction::UserRoleAssigned,
        AuditAction::SecurityEventScanRun,
        AuditAction::SecurityAlertRaised,
        AuditAction::SecurityEventAcknowledged,
        AuditAction::SecurityEventResolved,
        AuditAction::SecurityEventSuppressed,
        AuditAction::AutomatedResponseTriggered,
        AuditAction::StorageConnectionCreated,
        AuditAction::StorageConnectionChanged,
        AuditAction::StorageConnectionDeleted,
        AuditAction::StorageConnectionValidated,
        AuditAction::StorageSecretReplaced,
        AuditAction::StorageKeypairGenerated,
        AuditAction::StorageKeypairImported,
        AuditAction::StorageShareProvisioned,
        AuditAction::StorageShareRemoved,
        AuditAction::StorageMountProvisioned,
        AuditAction::StorageMountRemoved,
        AuditAction::ScourgeSensorConfigured,
        AuditAction::ScourgeRuleChanged,
        AuditAction::ScourgeModeChanged,
        AuditAction::ScourgeCaptureStarted,
        AuditAction::ScourgePcapDeleted,
        AuditAction::ScourgeSensorRemoved,
        AuditAction::ScourgeEventScanRun,
    ];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditOutcome {
    Success,
    Failure,
}

impl AuditOutcome {
    pub const fn as_key(self) -> &'static str {
        match self {
            AuditOutcome::Success => "SUCCESS",
            AuditOutcome::Failure => "FAILURE",
        }
    }
}
